betaflight/firmware-presets

index.json, indexer/PresetsFile.js, indexer/PresetsFolder.js, indexer/indexer.js, presets/TestSamples/4.2/4.2example.txt, presets/TestSamples/4.2/4.2example_2.txt, presets/TestSamples/4.2/defaults.txt, presets/TestSamples/4.2/rates/defaults.txt, presets/TestSamples/4.2/rates/rates_example1.txt, presets/TestSamples/4.2/rates/rates_example2.txt, presets/TestSamples/4.2/tune/defaults.txt, presets/TestSamples/4.2/tune/tuning_example_1 - Copy (2).txt, presets/TestSamples/4.2/tune/tuning_example_1 - Copy (3).txt, presets/TestSamples/4.2/tune/tuning_example_1 - Copy.txt, presets/TestSamples/4.2/tune/tuning_example_1.txt, presets/TestSamples/4.3/rates/defaults.txt, presets/TestSamples/4.3/rates/rates_example1.txt, presets/TestSamples/4.3/rates/rates_example2.txt, presets/TestSamples/4.3/tune/defaults.txt, presets/TestSamples/4.3/tune/tuning_example_1 - Copy (2).txt, presets/TestSamples/4.3/tune/tuning_example_1 - Copy (3).txt, presets/TestSamples/4.3/tune/tuning_example_1 - Copy.txt, presets/TestSamples/4.3/tune/tuning_example_1.txt
To run the indexer script from the repo root folder:
`node indexer/indexer.js`
this will create an index.json file representing the structure of the "presets" folder with subfolders and files.
Some preset txt samples are added as well to be removed later when the real presets are created.
Presets file is a file with a list of CLI commands and a header as comments in the following format:
```
<cli command 1>
<cli command 2>
....
<cli command n>
```
=> Indexer script and some presets samples for testing the script and Configurator functionality

README.md
=> add user focused content to readme

README.md
Added some details about how to create a preset
=> readMe: add note about creating presets

presets/4.3/rates/Directory_freestyle.txt
added my freestyle rates. the description explains the reasons why these rates are unique.
=> New freestyle rates preset

presets/4.3/rc_link/Crossfire_150hz_locked _CFV3.txt, presets/4.3/rc_link/Crossfire_150hz_locked_CFV2.txt, presets/4.3/rc_link/Crossfire_50hz_locked_CFV2_CFV3.txt, presets/4.3/rc_link/Crossfire_dyanmic_rate.txt, presets/4.3/rc_link/Tracer_CFV2.txt, presets/4.3/rc_link/Tracer_CFV3.txt, presets/4.3/rc_link/elrs_150hz.txt, presets/4.3/rc_link/elrs_250hz.txt, presets/4.3/rc_link/elrs_500hz.txt, presets/4.3/rc_link/elrs_50hz.txt, presets/4.3/rc_link/frsky_sbus.txt
fix typo and update feedforward_smoothing
=> Fix typos in rx_link presets

presets/4.3/rates/BMSThomas.txt
add @limonspb as author, add discussion link, throttle curve option and include default  file
=> update Bms rates

presets/4.3/tune/karate_race.txt
included missing #
thanks @limonspb for spotting these
=> fix mistakes

presets/4.3/tune/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt
Presets updates/improvements...
=> Supafly Freestyle Presets

presets/4.3/tune/tiny_karate.txt
This racing tune was developed for the 533 tiny trainer spec class  with @Shames throwing his quad out the window and sending me logs
with more further testing we can move from EXPERIMENTAL to COMMUNITY down the line
=> TinyTrainer karate tune

presets/4.3/tune/karate_race.txt
=> Karate fix

presets/4.3/vtx/HDZero_race2.txt
vtx table for new 20x20 race VTX from HDzero
manual found here
[HDzero race2 manual]( https://28003cc0-88ab-4618-8fa6-9747a051df97.filesusr.com/ugd/ea052e_18c5903fbb13440b8d3831a965ea8a37.pdf?fbclid=IwAR2MdGKn8dIcT90CAUp74sYg4ycZYn87aOQpy_Fe5KYzVkfovMFpVew2sok)
=> Create HDZero_race2 vtx table

presets/4.3/rates/defaults.txt
Default Betaflight rates are not Betaflight anymore :)
=> Fix 4.3 default rates

presets/4.3/rates/UAV_tech.txt
=> UAV Tech rates

presets/4.3/rates/Headsup533.txt
Famous 533 racing rates by Headsup - Evan Turner.
Unchecked option - close ACTUAL rates analogue.
=> Headsup rates

presets/4.3/rates/Chief.txt
#$ Option provides ACTUAL rates analogue.
=> Chief rates

presets/4.3/tune/karate_freestle.txt
This is the sugarK freestyle tune, its been test over the last few months by members of the UAVtech discord.. This is a starting point tune and has siders active so you can fine tune it easily.
=> karate freestyle 5” tune

presets/4.3/tune/karate_freestyle_5_inch.txt, presets/4.3/tune/karate_race.txt
fixed spelling mistakes in keywords
=> fixed spelling mistakes

presets/4.3/rates/MinChan.txt
#$ option provides close analogue in ACTUAL rates
=> MinChan rates

presets/4.3/rates/illusionfpv_freestyle.txt
=> IllusionFpv freestyle rates

presets/4.3/vtx/diatone_mamba_ultra_1000.txt
Diatone Mamba Ultra 1000 VTX tables HAM and NO HAM options.
Link to official VTX table json file: https://cdn.shopify.com/s/files/1/0027/2708/4144/files/Ultra_1000.rar
=> Add Diatone Mamba Ultra 1000 VTX tables

presets/4.3/rc_link/Crossfire_150hz_locked _CFV3.txt, presets/4.3/rc_link/Crossfire_150hz_locked_CFV2.txt, presets/4.3/rc_link/Crossfire_50hz_locked_CFV2_CFV3.txt, presets/4.3/rc_link/Crossfire_dyanmic_rate.txt, presets/4.3/rc_link/Tracer_CFV2.txt, presets/4.3/rc_link/Tracer_CFV3.txt, presets/4.3/rc_link/elrs_150hz.txt, presets/4.3/rc_link/elrs_250hz.txt, presets/4.3/rc_link/elrs_500hz.txt, presets/4.3/rc_link/elrs_50hz.txt, presets/4.3/rc_link/frsky_sbus.txt, presets/4.3/rc_smoothing/cinematic.txt, presets/4.3/rc_smoothing/freestyle.txt, presets/4.3/rc_smoothing/hd_freestyle.txt, presets/4.3/rc_smoothing/race.txt, presets/4.3/tune/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt, presets/4.3/tune/ctzsnooze_5in_4S_race.txt, presets/4.3/tune/defaults.txt, presets/4.3/tune/karate_freestyle_5_inch.txt, presets/4.3/tune/karate_race.txt, presets/4.3/tune/reset_all.txt, presets/4.3/tune/reset_some.txt, presets/4.3/tune/tiny_karate.txt
well... lol
feedforward_jitter_factor
d_max_gain
d_max_advance
=> Variables name fix: feedforward_jitter_factor, d_max_gain, d_max_advance

presets/4.3/filters/defaults.txt, presets/4.3/tune/defaults.txt
Well, i hope no more changes after that :)
=> Fix TUNE and FILTERS defaults to match with latest 4.3 defaults

presets/4.3/tune/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt
Hi Limon let me know is any issues thanks dude...
=> RC1 Updates

presets/4.3/rates/BMSThomas.txt
fix author for BMSThomas rates
=> BMSThomas rates: fix author

presets/4.3/tune/karate_freestyle_5_inch.txt, presets/4.3/tune/karate_race.txt, presets/4.3/tune/tiny_karate.txt
fixed the karate tunes to work with sliders in RC1
=> fixed  karate tunes for rc1

presets/4.3/vtx/HDZero_race2.txt
uses defaults_vtx_tables.txt now
=> Hdzero fix

presets/4.3/tune/karate_race.txt
finally brought this up to rc1 spec, i have returned  to the tried and  tested gyro LPF settings. note this tune isn't a slider tune.. trying to make it so has led to issues with it been overly sensitive
=> rc1 updates to karate race

presets/4.3/tune/whoop_justice.txt
Clarified some settings and tidied up.
Good to go, hopefully!
=> updates and fixes to Whoop tune from Justice

presets/4.3/tune/karate_race.txt
added tracer elrs and ghost options to the karate race tune
=> added race link options to karate race tune

misc/warnings/en/ADC.txt, presets/4.3/rc_link/IRC_freestyle.txt, presets/4.3/rc_link/IRC_longrange.txt, presets/4.3/rc_link/IRC_race.txt
presets in race, freestyle and longrange version.. 
and yes i have excluded mode that make no sense for the use
=> IRC Ghost preset

presets/4.3/rc_link/IRC_freestyle.txt, presets/4.3/rc_link/IRC_longrange.txt, presets/4.3/rc_link/IRC_race.txt
=> changed hz to Hz

presets/4.3/rc_link/defaults.txt
=> RC_LINK defaults: remove rx protocol from description

presets/4.3/vtx/NanoHawk.txt
Sorry, I closed the previous PR as I could not figure out how to ditch the two files from my PR that were updated by the indexer after running it.
If someone would like to explain me how to do that, please enlighten me.
=> Add NanoHawk preset

presets/4.3/tune/fpvian_basher_freestyle.txt
This PR adds the "Basher Freestyle 6S 5" by FPVian" experimental preset to the Betaflight Configurator.
=> Added fpvian_basher_freestyle preset

presets/4.3/tune/fpvian_basher_freestyle.txt
This PR modifies the exiting fpvian_basher_freestyle preset by adding Option Groups to organize most of the options.
=> Added Option Groups to fpvian_basher_freestyle Preset

presets/4.3/tune/fpvian_basher_freestyle.txt
This PR adds the Force_Options_Review setting to the fpvian_basher_freestyle preset.
=> Added Force_Options_Review Setting

presets/4.3/tune/whoop_ayyykayyy.txt
1S whoop brushless tune for acro racing.
AyyyKayyy - Whooptopia winner 2019, 2020, and 2021. Whooptopia - biggest and the most intense whoop race in the USA.
This tune does not require RPM and works with regular BLHELI_S
=> AyyyKayyy 1S whoop race tune

README.md
Update to ReadMe to include the new Options commands.
=> update readme with new Options stuff

presets/4.3/filters/BMI270_dual.txt
Weather is bad so can't provide more flight log, marked it as experimental.
=> Add dual BMI270 filter settings

presets/4.3/tune/UAV_tech_6-7in.txt
UAV Tech 6/7in Preset
PID Tab:
Filters Tab:
48K PWM Option:
=> UAV Tech 6/7in Preset

presets/4.3/rc_link/DJI_SBUS_Fast.txt
Added RC Smoothing per request.  Snagged from ELRS 250hz by CTZ.
=> DJI-SBUS-FAST (Update to Add RC Smoothing Factors)

presets/4.3/rc_link/DJI_Normal.txt
Added RC Smoothing per request.  Snagged from ELRS 250hz by CTZ.
=> DJI-Normal (Update to Add RC Smoothing Factors)

presets/4.3/tune/UAV_tech_5in.txt
UAV Tech 5" Preset
PID Tab:
Filters Tab:
48K PWM Option:
=> UAV Tech 5" Preset

presets/4.3/tune/UAV_tech_6-7in.txt
Tied to original PR #202 with updates
=> UAV Tech 6/7in Preset - UPDATED WARNINGS

presets/4.3/rates/UAV_tech.txt
Base Preset:
Cinematic/HD Smoothing:
Whooping in Angle\Horizon Mode:
=> Revising UAVtech Rates

presets/4.3/osd/UAV_tech_DJI_GPS.txt
=> Adding UAV_tech_DJI_GPS

presets/4.3/osd/UAV_tech_DJI.txt
=> Adding UAV_tech_DJI

presets/4.3/osd/UAV_tech_Analog.txt
=> Adding UAV_tech_Analog

presets/4.3/tune/UAV_tech_Whoop.txt
PID Tab:
Filters Tab:
48K Option:
96K Option:
=> Adding UAV_tech_Whoop

presets/4.3/tune/UAV_tech_Toothpic.txt
PID Tab:
Filters Tab:
48K Option:
96K Option:
=> Adding UAV_tech_Toothpic

presets/4.3/tune/UAV_tech_Cinewhoop.txt
PID Tab:
Filters Tab:
48K Option:
96K Option:
=> Adding UAV_tech_Cinewhoop

presets/4.3/tune/UAV_tech_8-9in_Cinelifter.txt
PID Tab:
Filters Tab:
48K Option:
=> Adding UAV_tech_8-9in_Cinelifter

presets/4.3/tune/UAV_tech_8-9in.txt
PID Tab:
Filters Tab:
48K Option:
=> Adding UAV_tech_8-9in

presets/4.3/tune/fpvian_basher_freestyle.txt
Title says it all. Changed the status of the fpvian_basher_freestyle preset from EXPERIMENTAL to COMMUNITY.
=> Changed fpvian_basher_freestyle to a COMMUNITY preset

presets/4.3/tune/defaults.txt
Fixes #225 and makes it clearer what integrated yaw does.
=> fix integrated yaw wording

presets/4.3/filters/dusking_BMI270.txt, presets/4.3/filters/dusking_BMI270_dual.txt
- Add "dusking_" prefix to the name
- Rename titles
- Update with latest release
=> Update bmi270 with the latest release

presets/4.3/tune/UAV_tech_6-7in.txt
Upgrades to the 6/7 in preset.
=> UAV Tech 6"/7" Tune Upgrades -- Updated AG to 5 and Improved Description

presets/4.3/vtx/HDZero.txt
added support for the full range of vtxs from HDzero
this update allows all vtx from HDzero to be setup from this preset
=> HDzero preset update

presets/4.3/tune/mouseFPV_AOS_35_tune_filters.txt
AOS 3.5 V1 Tune for Betaflight 4.3. Filters are included and optional.
=> Tune for the AOS 3.5 on Betaflight 4.3

presets/4.3/rates/mouseFreestyle.txt
copy of my freestyle rates. I have the status as community because I didn't see anything in the official repo with experimental, and rates are lower risk than something like a tune, but I can make that change as needed. as soon as this PR is created I will amend and add a link to this PR IE #$ DISCUSSION: https://github.com/betaflight/firmware-presets/pull/n
=> mouseFPV Freestyle Rates for betaflight 4.3

presets/4.3/rates/mouseFreestyle.txt
Adds the logo and some small reformatting for @rochford77's preset. Original PR is at https://github.com/betaflight/firmware-presets/pull/250
=> Enhance mouseFPV Freestyle Rates description

README.md
Figured that should be in the readme instead of me explaining that to every new author :)
=> Added the list of quick tips for the new preset authors

presets/4.3/tune/karate_race.txt
Follow-up to https://github.com/betaflight/firmware-presets/pull/258
Only minor markdown styling and an option group for sugarK's rates to visually separate it a bit more from the options above.
=> KarateTune: Stylize Description

presets/4.3/tune/UAV_tech_5in.txt
=> UAV Tech 5" Tune Upgrades -- Updated AG to 5 and Improved Description

presets/4.3/tune/UAV_tech_5in.txt
Update to #201 to have low gyro noise settings as an option vs. default.
=> Adding low gyro noise as an option (vs default)

presets/4.3/tune/karate_race.txt
Thanks to @ctzsnooze for pointing out that higher TPA values makes things less spicy :)
Removing this shame asap
Removed a few trailing spaces also
=> remove spicy TPA options cuz it's not actually spicy

presets/4.3/tune/karate_race_lite.txt
This racing tune was developed from the Karate Race tune to suit my new Viper lite ultralite 5" racer project. [Viper Lite](https://rotorbuilds.com/build/29775)
=> karate 'Viper Lite' race tune

presets/4.3/vtx/Avatar_HD.txt
I added a preset to configure MSP OSD for Walksnail Avatar HD VTX's
=> feat: add Avatar HD preset

presets/4.3/other/blackbox_disable.txt
add 4.4 tag to Blackbox Preset
=> Update blackbox_disable.txt to 4.4 tag

presets/4.3/tune/tiny_karate.txt
=> Update tiny_karate.txt to COMMUNITY

presets/4.3/vtx/Eachine_Nano_V2.txt, presets/4.3/vtx/Foxeer_Reaper_Extreme.txt, presets/4.3/vtx/NanoHawk.txt, presets/4.3/vtx/Unify_EVO_5G8_HV_SA.txt, presets/4.3/vtx/Unify_Pro32_HV_SA2_1.txt, presets/4.3/vtx/Unify_Pro32_Nano_SA2_1.txt, presets/4.3/vtx/Unify_Pro_HV_800mw_Unify_Pro_V3_SA_2_0.txt, presets/4.3/vtx/Unify_Pro_HV_Race_Not_Race_V2_SA2_0.txt, presets/4.3/vtx/Unify_Pro_HV_Race_V2 _SA2_1.txt, presets/4.3/vtx/Unify_Pro_Nano_SA2_0_lite.txt, presets/4.3/vtx/diatone_mamba_ultra_1000.txt, presets/4.3/vtx/eachine_vtx.txt, presets/4.3/vtx/rush_sa2.1_vtx_tables.txt, presets/4.3/vtx/speedybee_tx800.txt, presets/4.3/vtx/tramp_nano_and_HV.txt
add 4.4 tag to all non MSP vtx tables
=> add 4.4 tag to all non msp vtx tables

presets/4.4/other/Tehllama_5in_Race_Spec_Multi.txt
Reference #307 - changed preset type to Experimental.
=> Modify Status to Experimental for Llama 5in Spec-ONLY Multivoltage Tune

presets/4.3/tune/minchan_2022_race.txt
Tune values provided as-is from MinChan's quad diff to be authentic.
=> Added MinChan 2022 race tune

presets/4.3/rates/BMSThomas.txt, presets/4.3/rates/Bardwell.txt, presets/4.3/rates/CGo.txt, presets/4.3/rates/Chief.txt, presets/4.3/rates/Directory_freestyle.txt, presets/4.3/rates/Feisar_freestyle.txt, presets/4.3/rates/Garban_race.txt, presets/4.3/rates/Headsup533.txt, presets/4.3/rates/MinChan.txt, presets/4.3/rates/UAV_tech.txt, presets/4.3/rates/ctzsnooze_race.txt, presets/4.3/rates/defaults.txt, presets/4.3/rates/illusionfpv_freestyle.txt, presets/4.3/rates/limon.txt, presets/4.3/rates/mouseFreestyle.txt
Added 4.4 firmware tag to all rates
Some indentations and trailing spaces fixes
=> Added 4.4 firmware tag to all rates

presets/4.3/filters/basic_no_rpm_clean.txt, presets/4.3/filters/basic_no_rpm_noisy.txt, presets/4.3/filters/basic_no_rpm_normal.txt, presets/4.3/filters/basic_no_rpm_very_clean.txt, presets/4.3/filters/basic_no_rpm_very_noisy.txt, presets/4.3/filters/basic_rpm_clean.txt, presets/4.3/filters/basic_rpm_noisy.txt, presets/4.3/filters/basic_rpm_normal.txt, presets/4.3/filters/basic_rpm_very_clean.txt, presets/4.3/filters/basic_rpm_very_noisy.txt, presets/4.3/filters/ctzsnooze_race.txt, presets/4.3/filters/defaults.txt, presets/4.3/filters/dusking_BMI270.txt, presets/4.3/filters/dusking_BMI270_dual.txt
4.4 filters are the same as 4.3, so just adding 4.4 to filters
And some indentations
=> Added 4.4 firmware to all filters

presets/4.4/tune/Street_League_LeadFingers.txt, presets/4.4/tune/ctzsnooze_5in_4S_race.txt, presets/4.4/tune/defaults_tune_filters.txt, presets/4.4/tune/fpvian_basher_freestyle.txt, presets/4.4/tune/freedom_spec_460g.txt, presets/4.4/tune/whoop_ayyykayyy.txt, presets/4.4/tune/whoop_justice.txt
@ctzsnooze  @FPVian @LeadFingers 
I ported your tunes here to 4.4, but in future, they still require review because of the new AG in 4.4
=> Porting some misc tunes to 4.4 from 4.3

presets/4.4/other/Tehllama_5in_Race_Spec_Multi.txt
Same as #324 - Reducing the RPMF FadeRangeHz down to 77.
=> Llama 5in Spec Multivoltage Half Power Tune - Fix Spicy Tune RPM Filter Fade Range to 77

presets/4.3/vtx/Avatar_HD.txt, presets/4.4/vtx/DJI_FPV-WTF_MSP-OSD.txt, presets/4.4/vtx/HDZero.txt
makes these presets 4.4 compatible and fixes style issues
=> fixes up Hd osd presets to suit 4.4 changes

presets/4.4/tune/uav_tech/UAV_tech_Whoop.txt
=> UAV_tech_Whoop

presets/4.4/tune/uav_tech/UAV_tech_Cinewhoop.txt
=> UAV_tech_Cinewhoop

presets/4.4/tune/uav_tech/UAV_tech_10in.txt
=> UAV_tech_10in

presets/4.4/tune/uav_tech/UAV_tech_Cinelog.txt
=> UAV_tech_Cinelog

presets/4.4/tune/uav_tech/UAV_tech_8-9in.txt
=> UAV_tech_8-9in

presets/4.3/tune/SupaflyFPV_Freestyle_3_4_Inch_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_3_4_Inch_EasyTune.txt
Here is a new preset for 3 to 4 Inch quads for 4.3, with included PIDs, Filters, Radio and Rates setup for freestyle
=> 3 4 Inch Tune for 4.3 Presets

presets/4.3/tune/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt
Following on from yesterdays adventure, here are the updates for 4.3 and 4.4 Supafly Tune
=> 5 Inch Tune Updates

presets/4.4/tune/karate/karate_brushless_whoop.txt, presets/4.4/tune/karate/karate_freestyle_5_inch.txt, presets/4.4/tune/karate/karate_race.txt, presets/4.4/tune/karate/karate_race_lite.txt
updated karate 6s tune to slider
and added suagrK rates as a file to all karate tunes
along with the RClink files
=> updated karate tunes

presets/4.3/tune/SupaflyFPV_Freestyle_3_4_Inch_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_3_4_Inch_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt
I put the changes, which are similar to the last PR, into one to save time...let me know if thats a problem...
=> 4.3 Tune Updates for 5/6/7 Inch

presets/4.4/rates/DavideFPVFreeStyle.txt
I wish to add my rates to the Betaflight community presets tab. Here is Davide FPV (Davide Angeletti), a Professional Italian Pilot and Vocational Trainer, Youtube content creator, and professional tuner. YT Channel:  [https://www.youtube.com/davidefpv](https://www.youtube.com/davidefpv) IG and TikTok: @davidefpv. 
Thanks a lot and happy flying!
=> Add davidefpv rates

presets/4.3/rc_link/generic/1000hz_race.txt, presets/4.4/tune/karate/karate_race.txt, presets/4.4/tune/karate/karate_race_lite.txt
update a few of the karate presets and adding elrs to the keywords on the 1000hz preset
=> update a few of my presets

presets/4.4/vtx/DJI_FPV-WTF_MSP-OSD.txt, presets/4.4/vtx/HDZero.txt
update the hd presets to use HDOSD now that all platforms can use it. also made sure 7 uarts can be set
=> update HD presets

presets/4.4/tune/uav_tech/UAV_tech_5in_Freestyle_650-750.txt
Updated to Community and tweaked Dyn Idle so it sets correctly without having to set RPM filter to Enable.  Also upped anti-gravity.
=> UAV_tech_5in_Freestyle_650-750 -- TWEAKS

presets/4.4/tune/fpvian_basher_freestyle.txt
I did some testing with the new AG and decided to leave it at defaults. Defaults just keep getting better and better.
=> Fix firmware version in FPVian freestyle 5in tune

presets/4.4/osd/QuadMcFly_DJI_HD_OSD.txt
HD OSD Preset for DJI goggles without GPS
=> Add QuadMcFly HD OSD Preset

presets/4.4/rates/QuadMcFly_Freestyle.txt
Snappy freestyle rates from QuadMcFly
=> Add QuadMcFly Freestyle Rates

presets/4.4/tune/fpvian_basher_freestyle.txt
This preset has been tested on 4.4 now.
=> Change fpvian_basher_freestyle to community status

presets/4.4/leds/quaddition TT leds.txt
Sets LED settings to suit used VTX channels used by the quaddiction Tiny Trainer spec team
=> Create quaddition TT leds.txt

presets/4.4/leds/quaddiction_tinytrainer.txt
Fixes the whitespaces in the filename (and some other minimalistic fixes)
=> Fix quaddiction preset

presets/4.3/tune/UAV_tech_Whoop.txt, presets/4.3/tune/whoop_ayyykayyy.txt, presets/4.3/tune/whoop_justice.txt, presets/4.4/tune/uav_tech/UAV_tech_Whoop.txt, presets/4.4/tune/whoop_ayyykayyy.txt, presets/4.4/tune/whoop_justice.txt
i think it's safe to set 12 poles for whoops no matter what.
whoop guys started running RPM spec, and that becomes critical.
=> adding 12 motor poles to whoop tunes

presets/4.4/tune/karate/karate_brushless_whoop.txt
missed one in https://github.com/betaflight/firmware-presets/pull/401
=> Karate whoop 4.4, added 12 motor poles

presets/4.5/tune/defaults.txt, presets/4.5/tune/karate/karate_brushless_whoop.txt, presets/4.5/tune/karate/karate_freestyle_5_inch.txt, presets/4.5/tune/karate/karate_race.txt, presets/4.5/tune/karate/karate_race_lite.txt, presets/4.5/tune/karate/tiny_karate.txt
updated 4.5 default file for tunes as the level mode stuff has changed and moved karate tunes to 4.5
=> fix default tune file for 4.5 and move karate tunes to 4.5

presets/4.4/tune/fpvian_basher_freestyle.txt
added 4.5 to list of supported firmware versions
=> Update fpvian preset to 4.5

presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_3_4_Inch_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt
Updating 4.4 presets to 4.5
pls forgive 4 files at once, wasn't sure how to split
=> Supafly 4.5 Tune Updates

presets/4.4/vtx/DJI_FPV-WTF_MSP-OSD.txt
For this issue:
https://github.com/betaflight/firmware-presets/issues/436
=> Update DJI_FPV-WTF_MSP-OSD.txt with 4.5 firmware

presets/4.3/vtx/JHEMCU_VTX30-800.txt
VTX table received from manufacturers directly
=> add VTX table for JHEMCU 30-800

presets/4.3/vtx/darwinfpv_vtx_25-200-400-600.txt, presets/4.3/vtx/jhemcu_vtx20-600.txt
I corrected errors in the previous PR
=> fix vtx presets

presets/4.5/tune/openracer_jazzmutant_tune.txt
Created preset for OpenRacer 6S 5 inch build
=> Added OpenRacer preset by JazzMutant

presets/4.5/tune/ozr_5x.txt
5" frame racing tune by Dindrones and Benjamin Freelove
=> ozr-5x tune preset BF 4.5

presets/4.5/tune/karate/karate_brushless_whoop.txt
a few little changes too the karate whoop preset
=> some changes to the karate whoop

presets/4.4/osd/YarosFPV_DJI_O3_OSD.txt
Added my OSD profile for DJI O3 Quads
=> Added YarosFPV DJI O3 OSD Preset

presets/4.5/filters/aos_rc/aos_hs5_filters.txt, presets/4.5/tune/aos_rc/aos_hs5_tune.txt
Hi Everyone!
I'm releasing a new frame tomorrow the AOS HS5🎉. It's a 200+ mph (320+ kph) capable 5" chase drone for filming the fastest racing cars and bikes. 
It needs a preset! 😁
=> added AOS HS5 preset

presets/4.5/filters/aos_rc/aos_ul10_filters.txt, presets/4.5/tune/aos_rc/aos_ul10_tune.txt
Another filter and PID tune for an AOS frame along the same lines as previous submissions. This is for the AOS UL10.
Many thanks to all the Betaflight team. 😁
=> Add tune for UL10

presets/4.5/filters/aos_rc/aos_ul10_filters.txt, presets/4.5/filters/aos_rc/aos_ul8_filters.txt, presets/4.5/tune/aos_rc/aos_ul8_tune.txt
Hi Betaflight team!
Another day another preset. This one is for the AOS UL8 frame. The same format as previous submissions.
Please let me know if any changes are needed.
=> AOS UL8 Filter and Tune

presets/4.5/tune/openracer_jazzmutant_tune.txt
Based on the feedback from the community I've changed something:
- tested it with 2100kv motors
- lowered master muliplier to reduce motor heat
- added thrust linearization to improve low throttle handling
- increased dynamic idle for newer props with lower pitch
=> update preset based on feedback
