indexer/PresetsFolder.js
After discussion with @ctzsnooze figured we need to skip .* files and folders while indexing presets.
Also decided to skip all non-txt files to be safe.
=> Skip .* files/folders and non txt files for presets indexing

indexer/check.js, indexer/indexer.js
usage:
`node indexer/indexer.js` - runs verifications for presets, creates index.json
`node indexer/indexer.js nosave` - just runs verifications
`node indexer/check.js` - just runs verifications, same as `node indexer/indexer.js nosave`
exit code 0 - no errors
=> Added indexer/check.js to run verifications without creating index.json

indexer/Settings.js
I apologize, forgot to do it long ago.
Readme is already updated by @ctzsnooze and correctly shows `#$ HIDDEN`, not `#$ NOSEARCH`
=> Attribute renamed NOSEARCH to HIDDEN

presets/4.3/tune/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_7_Inch_EasyTune
SupaflyFPV Freestyle EasyTune
This preset should be applicable to a wide variety of of freetyle builds, and easily tuned using the Master Multiplier Slider.
I think the slider positions correlate quite well with the main Betaflight default when considering the needs of freestyle, and I have taken a policy of leaving any exotic ideas for parameters out and settling for Betaflight defaults and philosophies rather than splitting hairs.
Those 'needs' of freestyle are no great surprise - more PIDs on the pitch axis due to typical freestyle frame design and HD camera...slightly higher D gain for propwash...some of my 'subjective' preferences such as moderate I gains, FF Jitter at 12, Moderate FF, med-heavy static Dterm filtering, reduced Gyro filters to cover the main noise issues robustly and …
=> SupaflyFpv Freestyle EasyTune

presets/4.3/rates/CGo.txt
Racing rates from Chris Go (Cgo), fastest pilot in NSW Australia and leader of the Quaddiction krew.
=> CGo rates preset

presets/4.3/rates/Bardwell.txt
#$ Option provides optional almost identical ACTUAL rates. By default - original JB rates
=> Bardwell rates

presets/4.3/rates/Vanover.txt
#$ option provides also actual rates close analogue.
=> Vanover rates

presets/4.3/rates/limon.txt
#$ option provides close analogue in BETAFLIGHT rates
=> limon rates

presets/4.3/filters/ctzsnooze_race.txt, presets/4.3/filters/default_rpm_clean.txt, presets/4.3/filters/default_rpm_noisy.txt, presets/4.3/filters/default_rpm_normal.txt, presets/4.3/filters/default_rpm_very_clean.txt, presets/4.3/filters/default_rpm_very_noisy.txt
Updates the default filter Presets with support for the changed filter slider behaviours now introduced to 4.3
In most cases just enables the gyro lowpass slider, which now works fine while running only one gyro lowpass in the RPM filter enabled presets.
This will allow a user to apply the gyro filter slider to change their gyro filtering, even if they are only running a single gyro lowpass 2 filter.
=> update filters for updated 4.3 slider behaviour

presets/4.3/other/blackbox_disable.txt
this preset alloys to disable logging of the individual data streams in blackbox. useful for saving space or CPU resources on less powerful chipsets.
=> Blackbox field disable preset

presets/4.3/vtx/speedybee_tx800.txt
Added the SpeedyBee TX800 tables for both EU and US
Link to official VTX Table json file for EU: https://speedybee.s3.amazonaws.com/vtxtable/betaflight/TX800/SpeedyBee-TX800(EU).json
Link to official VTX Table json file for US: https://speedybee.s3.amazonaws.com/vtxtable/betaflight/TX800/SpeedyBee-TX800(USA).json
=> Add SpeedyBee TX800 VTX Tables EU and US

presets/4.3/vtx/diatone_mamba_ultra_1000.txt
Fix mamba spelling in the tags.
Add IRC Tramp to description.
=> Fix mamba spelling and and IRC Tramp description

misc/warnings/en/dshot.txt, presets/4.3/filters/defaults.txt, presets/4.3/tune/freedom_spec_460g.txt
credits to @sugaarK  and @ctzsnooze 
This tune is not 100% done yet, that's why it is experimantal.
For freedom spec the focus is on clean motor traces at full throttle to make sure the drone does not loose speed because of the extra noisy motor traces. This one seems to be ok so far:
While still maintaining a good setpoint tracking:
there is still some propwash after full throttle sharp 180 turns, but it is moderate.
[logs.zip](https://github.com/betaflight/firmware-presets/files/7744690/logs.zip)
=> Freedom spec tune

README.md, presets/4.3/filters/defaults.txt
Removing motor_pwm_protocol from filters/defaults.txt:
And adding this to readme:
=> Clarifications about setting a motor protocol

presets/4.3/tune/whoop_justice.txt
Official whoop tune based on Gary Kent's carefully tuned 65mm 1S build.
The default values are a little softer than the 'spicy' option that Gary normally flies.  Both are quite aggressive and require a really good strong build.
A 'safer' tune option is provided for people with softer frames.  It still is quite aggressive.  If it wobbles, shakes, or climbs to the moon, pull the master slider back until it doesn't do those kinds of things.
If you use a 250hz or 500hz RC link, check the relevant box, and the appropriate feedforward smoothing and jitter reduction settings will be applied.
Needs updating with Gary's rates, and some other minor modifications - not for merging right now.
=> whoop tune by Justice (Gary Kent)

presets/4.3/tune/whoop_justice.txt
Initial build didn't give user a 'normal tune' option, because it was already applied.
User now chooses
- spicy (Gary's regular tune, on his well maintained quads)
- normal (Slightly softer, for people who occasionally have bent props)
- safer (for people with well used whoops)
=> add normal tune to Justice's Whoop PR

presets/4.3/tune/freedom_spec_460g.txt
dshot_idle_value does not matter in this preset because dynamic idle is being used anyways.
=> FreedomSpec Tune: remove dshot_idle_value

presets/4.3/tune/ctzsnooze_5in_4S_race.txt
Add basic 250 and 500hz RC link feedforward settings to help users quickly get that about right.
=> add rc link option to ctzsnooze 4S race tune

presets/4.3/vtx/OpenVTx.txt
This PR adds default VTx tables for the OpenVTx project. https://github.com/OpenVTx/OpenVTx
Currently there are 2 HappyModel and a NamelessRC VTx available.
=> adds openvtx preset

presets/4.3/tune/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt
`set simplified_dterm/gyro_filter_multiplier = 0` is not necessary and it is an invalid value (breaks firmware + configurator)
`set simplified_gyro/dterm_filter = OFF` should be enough.
Thanks to MikeNomatter from BF slack for noticing a problem with some presets.
=> removing set simplified_dterm_filter_multiplier = 0 from Supa tunes

presets/4.3/rc_link/DJI_SBUS_Fast.txt
DJI "SBUS Fast" protocol preset.
Settings/Option under this preset include ---
Race feedforward settings:
HD Freestyle feedforward settings:
Cinematch feedforward settings:
=> Added DJI SBUS Fast RC_Link Preset

presets/4.3/rc_link/DJI_Normal.txt
DJI "Normal" protocol preset.
Settings/Option under this preset include ---
Race feedforward settings:
HD Freestyle feedforward settings:
Cinematch feedforward settings:
=> Added DJI Normal RC_Link Preset

presets/4.3/rates/Garban_race.txt
Racing rates from Josep de la Fuente (Garban), one of the fastest pilot in Catalonia
With 482 deg/sec on roll, pitch and  yaw
Also with a throttle curve in order to improve low throttle
Still using Betaflight Rates.
and a comparison of the percentages of change in each stick position with other fastest pilot rates
=> Garban rates

indexer/PresetsFile.js, indexer/Settings.js, presets/4.3/tune/freedom_spec_460g.txt
Allowing [Marked ](https://marked.js.org/)for presets description to make them nicer.
new optional metaproperty:
`#$ PARSER: MARKED/TEXT`
default is TEXT
Corresponding Configurator PR:
https://github.com/betaflight/betaflight-configurator/pull/2841
Example:
To test:
Download Configurator from the configurator PR.
Add custom preset source - yours or this one:
link: https://github.com/limonspb/firmware-presets
branch: marked-demo
=> Added parser metaproperty: text/marked

presets/4.3/rc_link/defaults.txt, presets/4.3/rc_link/elrs_150hz.txt, presets/4.3/rc_link/elrs_250hz.txt, presets/4.3/rc_link/elrs_500hz.txt, presets/4.3/rc_link/elrs_50hz.txt, presets/4.3/rc_link/frsky_sbus.txt, presets/4.3/rc_link/redpine_mpm.txt, presets/4.3/rc_smoothing/cinematic.txt, presets/4.3/rc_smoothing/freestyle.txt
This is an early draft of how we might include smoothing options within RC links.
The intent is to get, as much as possible, similar stick feel for each 'fine tuning' option, and an appropriate balance between feedforward noise and stick responsiveness.
=> add smoothing options to links

presets/4.3/tune/whoop_justice.txt
This PR removes the 'Clean' filter option from Justice's whoop preset, since many people were choosing it on builds that couldn't handle it, and not knowing why things didn't work out so great.
A clean filter Preset can still be applied as a second independent action, if desired.
Option groups have also been used to organise the options a bit better.
=> Remove clean filter option from justice's whoop preset

presets/4.3/rc_link/generic/150hz_cinematic.txt, presets/4.3/rc_link/generic/150hz_freestyle.txt, presets/4.3/rc_link/generic/150hz_hd_freestyle.txt, presets/4.3/rc_link/generic/150hz_race.txt, presets/4.3/rc_link/generic/150hz_ultra_cinematic.txt, presets/4.3/rc_link/generic/250hz_cinematic.txt, presets/4.3/rc_link/generic/250hz_freestyle.txt, presets/4.3/rc_link/generic/250hz_hd_freestyle.txt, presets/4.3/rc_link/generic/250hz_race.txt, presets/4.3/rc_link/generic/250hz_ultra_cinematic.txt, presets/4.3/rc_link/generic/500hz_cinematic.txt, presets/4.3/rc_link/generic/500hz_freestyle.txt, presets/4.3/rc_link/generic/500hz_hd_freestyle.txt, presets/4.3/rc_link/generic/500hz_race.txt, presets/4.3/rc_link/generic/500hz_ultra_cinematic.txt, presets/4.3/rc_link/generic/50hz_cinematic.txt, presets/4.3/rc_link/generic/50hz_freestyle.txt, presets/4.3/rc_link/generic/50hz_hd_freestyle.txt, presets/4.3/rc_link/generic/50hz_race.txt, presets/4.3/rc_link/generic/50hz_ultra_cinematic.txt
Next step for removing the RC_SMOOTHING category.
Those are just ERLS presets separated by Hz and flying purpose into separate files.
Now ghost/tracer/crossfire presets will be able to #$ INCLUDE these presets.
=> Added generic RC link presets: 50hz, 150hz, 250hz, 500hz

presets/4.3/filters/defaults.txt
The default for Betaflight (after the Reset button) is that the RPM filter is OFF.  However, the default Filter preset has the RPM filter enabled.  This change turns it OFF to be more consistent with the true default.
=> RPM off by Default

presets/4.3/other/gyroflow_min_blackbox.txt
Disables all blackblox fields which are not necessary to use [Gyroflow](https://gyroflow.xyz). Only gyro data will be recorded at the lowest logging rate possible. This allows for smaller blackbox files, longer blackbox recordings and lower CPU overhead.
The space gain is substantial. For every 10 seconds of flight, with the minimum configuration the space occupied is approximately 32.5kB and for a typical blackbox configuration (debug mode in Gyro_scaled and a rate of 2kHz) the occupation is 574.7kB
These values are approximate and should be taken as an example. Every drone and every flight are different.
=> Gyroflow minimum blackbox settings

presets/4.3/tune/freedom_spec_460g.txt
Making freedom spec preset COMMUNITY after massive testing by a lot of pilots.
31 pilots voted (International race hosted in Costa Rica, 2022):
Also adding an option for the noisy frames that have resonances 100hz-180hz.
Saw two freedom  spec quads like that with long 6 inch arms (CWM Merica Frame)
Also fixed indentation for the options
=> Freedom spec tune: make COMMUNITY, add noise frame option

presets/4.3/vtx/Eachine_Nano_V2.txt
I forgot to change the ids when I remove the BOSCAM_E band and the power levels were for TBS SA but it's an IRC Tramp VTX (copy paste from another VTX)
My bad
=> Wrong band ids and power levels

presets/4.3/filters/defaults.txt
Considering this PR:
https://github.com/betaflight/firmware-presets/pull/232
need to add 
`set gyro_hardware_lpf = NORMAL`
to filer **defaults** for 4.3
=> Add gyro_hardware_lpf = NORMAL to filter defaults

presets/4.3/other/ELRS_Passthrough.txt
Probably the laziest preset ever... but just a quick utility preset that puts the serialrx_halfduplex and serialrx_inverted to default (off) values, and disables telemetry.
=> Create ExpressLRS Betalight Passthrough Preset

package.json
allows people to run the scripts, without having a diverging package.json or a stoneage node version
=> allow for later node versions

presets/4.3/other/Tehllama_5in_1900-2250KV_FreedomSpec_3S-5S-6S_Race_TUNE_OTHER.txt
Official repo version of the Tehllama Multivoltage Tune Preset (with options that color outside the lines) used for FreedomSpec and TexasSpec quads in this KV range.
Biggest known limitation is plugging in a 4S battery with the 3S tune selected, expectation is HOT motors and marginal performance (but works great with 5/6S profiles selected).
The profile auto-select has been invaluable for me on rigs that get used as Freedom spec and open class racers, the flexibility and stupid-proofing of profile selection has been a massive help.
The multi-voltage filters are a bit of a singular package, but have been extensively tested on a lot of builds, from multiple builders.
End result is a softer tune than the Karate setup, this does allow some propwash at the ~480g AUW for FreedomSpec, but is …
=> TehLlama FreedomSpec & TexasSpec 1900-2250KV 3/5/6S MultiVoltage Preset (OTHER/Tune)

presets/4.3/other/Tehllama_5in_2350-2750KV-TexasSpec_3S-4S-5S_Race_TUNE_OTHER.txt
Official repo version of the Tehllama Multivoltage Tune Preset (with options that color outside the lines) used for emulating FreedomSpec using the TexasSpec calculator for quads in this KV range.
Biggest known limitation is plugging in a 6S battery is BAD, especially with the 3S tune selected, expectation is HOT motors and marginal performance with 4S profiles selected, and basically guaranteed bad things with the 3S tune using the FreedomSpec gains.
The profile auto-select has been invaluable for me on rigs that get used as TesasSpec and open class racers, the flexibility and stupid-proofing of profile selection has been a massive help.
The multi-voltage filters are a bit of a singular package, but have been extensively tested on a lot of builds, from multiple builders.
End result is a …
=> TehLlama TexasSpec 2300-2750KV 3/4/5S MultiVoltage Preset (OTHER/Tune)

presets/4.3/other/Tehllama_5in_BMS-Spec_1600-2350KV_4S-5S-6S_Race_TUNE-OTHER.txt
Official repo version of the Tehllama Multivoltage Tune Preset for lowKV (with options that color outside the lines).
The profile auto-select has been invaluable for me on rigs that get used as TesasSpec and open class racers, the flexibility and stupid-proofing of profile selection has been a massive help.
The multi-voltage filters are a bit of a singular package, but have been extensively tested on a lot of builds, from multiple builders.
End result is a softer tune than the Karate setup, this does allow some propwash at the ~480g AUW for FreedomSpec, but is actually a solid alternative to the Karate tune for the open configurations. I recommend trying this for anybody that has a quad that struggles on the Karate tune (but since this is an 'other' preset, strongly recommend a full chip …
=> TehLlama BMS-Spec 1600-2150KV 4/5/6S MultiVoltage Preset (OTHER/Tune)

presets/4.3/vtx/HDZero.txt
The HDZero logo had a lot of unused transparent border on the top and bottom so I cut it off with my html scissors ✂
=> HDZero VTXs: Fix border size

presets/4.3/tune/Tehllama_533_TinyTrainer_3in_3S_TUNE_Options.txt
This is a PR to adapt the existing 533 Tiny Trainer Tune developed by Armando and Evan for the TinyTrainer spec class setups.
This tune is a 4.3 adaptation leveraging the SDFT and adjusting the RPM Idle parameters slightly, and works on a variety of non-spec motor/prop configurations as well *( So far tested on Emax Eco 1404, Talon 1404+, Xing 1404, TMotor 1404, Mamba 1404, Mamba 1105, GEPRC 1404, BetaFPV 1404, and Foxeer 1404).
=> Create Tehllama 533_TinyTrainer 3in_3S_TUNE Preset

presets/4.3/other/Tehllama_GTB339_3in_SWPR-Spec_2S-3S_Race_TUNE_OTHER.txt
Official repo version of the Tehllama Multivoltage Tune Preset for the SWPR Spec GTB339 (or similar Mamba 1105 5500KV setups).
This has been tested on GEPRC and BetaFPV 1105 motors, RCINPower 1204 Motors, and even FPVCycle 1303 motors, and works remarkably well.  Frames tested include the GTB 339 Cube frame, Babytooth, TP3, Talon BirdOfPrey, Armattan Gecko, BetaFPV XKnight, and TwigXL.
The profile auto-select has been invaluable for me on rigs that get used as spec and open class racers, the flexibility and stupid-proofing of profile selection has been a massive help.
The multi-voltage filters are a bit of a singular package, but have been extensively tested on a lot of builds, from multiple builders.
=> Added Llama SWPR Spec Tune for GTB339 3in on 2S or 3S (Works with TP3 1303 5000KV Builds)

presets/4.3/tune/karate_race.txt
1. Added experimental BOSH option
2. Reduced AG gain to 3.0
3. Adding corresponding rc_smoothing to the RC_LINK options
4. Replaced limon's spicy D gain with Spicy TPA
5. Added options_group for RC_LINKS for better look
6. Added indentation to the code
Original Karate PR:
https://github.com/betaflight/firmware-presets/pull/41
=> Karate Race 6S polishing

presets/4.3/other/Street_League_motor_outputs.txt, presets/4.3/tune/Street_League_LeadFingers.txt
adds a Street League spec Motor output and throttle limit setting to the "other" preset
adds a LeadFingers PidToolbox tune for Street League quads.
=> added Street League preset tune and motor output limit

presets/4.3/other/Tehllama_5in_2350-2750KV-TexasSpec_3S-4S-5S_Race_TUNE_OTHER.txt, presets/4.3/tune/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.3/tune/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt, presets/4.3/tune/ctzsnooze_5in_4S_race.txt, presets/4.3/tune/defaults.txt, presets/4.3/tune/fpvian_basher_freestyle.txt, presets/4.3/tune/karate_freestyle_5_inch.txt, presets/4.3/tune/mouseFPV_AOS_35_tune_filters.txt, presets/4.3/tune/reset_all.txt, presets/4.3/tune/reset_some.txt, presets/4.3/tune/tiny_karate.txt, presets/4.3/tune/whoop_justice.txt
Both `feedforward_jitter_factor` and `feedforward_averaging` are parts of the RC_LINK category
so TUNEs don't need and can't set these values. Unless inside the RC_LINK options.
The final CLI outcome must be the same regardless of the order that user applies presets (RC_LINK + TUNE == TUNE + RC_LINK)
So i removed `feedforward_jitter_factor` from tune/defaults.txt
removed `feedforward_jitter_factor` and `feedforward_averaging` from the tunes
replaced old RC_LINK options in the tunes with the proper `#$ INCLUDE rc_link/....`
Please check the changes with care.
=> Removed feedforward_jitter_factor and feedforward_averaging froom TUNE

presets/4.3/tune/mouseFPV_AOS_35_tune_filters.txt
Original preset pr: https://github.com/betaflight/firmware-presets/pull/247
This update brings my AOS 3.5 tune in line with my Incisor tune in terms of structure, methodology, and formatting, and brings forward feedback and lessons learned in that tune. 
We now load the default filters along with the default pids, then set filters that work without bidirectional dshot. no motor protocol is set in the base. 
We continue to have options for f4 and f7 rpm filters. They re-load default filters, set proper dshot protocol for MCU, enables bi-directional, then apply RPM filtering. the f4 uses dshot 300 and has gyro lfp2 at 1000hz and recommends 4k pidloop in the description. the f7 uses dshot600, has no gyro lpfs, and recommends n 8k pidloop. 
we also use the default dshot warning, and the …
=> Adds default filter setup to SDFT, updates description, updates warning

presets/4.3/tune/mouseFPV_toothpick3_3s.txt
This is a preset for 3" toothpick builds. 
Offers SDFT filters in the main preset, and has options for RPMf on f4 or f7, and those set dshot accordingly. We also have a dyn_idle option that does not set dshot or bi-directional, so it will fail silently/gracefully if those aren't on (the value just wont do anything. 
The TP3 is a fully symmetrical machine, true x with even mass distribution, other than the lipo. The lipo in this quad is side mount, so it goes against BF standard practice and actually has higher gains on roll than pitch because of this. However, similar frames that mount the lipo front to back, or an improper build of the tp3 with the lipo going front to back would need the pid values "flipped" about pitch and roll, such that gains were higher on pitch. There is an option …
=> Creating Preset for Toothpick 3 on 3s

presets/4.3/tune/mouseFPV_Digipick_braced.txt
The toothpick class of frames has a small weight window before things get out of control. The target weight is usually about 100g
When you go digital and add weight to the quad, things get a bit unstable. You would usually increase the PID's to make up for this, however a normal toothpick frame cannot handle this.
If you brace the arms, or the frame has a design that incorporates a trussed arm system, you can push the gains much higher and get a far better flying craft
This tune is made to specifically push the pids beyond the boundary of what most "standard" arm toothpick class quads would normally handle.
I will update the discussion tag to have this pr# once it is created
=> Create mouseFPV preset for Braced digipick/toothpicks

presets/4.3/tune/mouseFPV_FPVCycle_Sonicare_tune_filters.txt
The FPVCycle Sonicare is a new frame from FPVCycle. This frame has a unique wishbone arm design that uses 8 individual arm members to build the 4 arms. This quad has amazing resonance performance and very little low freq noise, meaning we can push the pids pretty far and reduce filtering significantly.
This tune loads the default tune and filters, then applies a non-rpm filtering setup as well as proper pids. There are options for ds300/600 RPM filtering setups that re-load the default filters, apply the proper dshot and filter settings. dshot300 assumes a 4k pidloop will be needed, and thus adds in an lpf2 on the gyro.
There is a dynamic idle option that does not enable dshot, so if things are not properly setup, it will set the value but it wont actually do anything.
=> Create mouseFPV preset for FPVCycle Sonicare

presets/4.3/tune/freedom_spec_460g.txt
Small fix,
default 3500 for AG gain is just way too high for 4.3 causing problems on fast throttle moves.
Making it 2000
=> Freedom Spec tune: fix anti gravity gain to 2000

presets/4.3/vtx/Foxeer_Reaper_Extreme.txt, presets/4.3/vtx/Unify_Pro_HV_800mw_Unify_Pro_V3_SA_2_0.txt
VTX link:
https://www.foxeer.com/foxeer-5-8g-reaper-extreme-2-5w-40ch-vtx-g-444
The manufacturer didn't provide regulatory domains, so there we go, as is.
=> Added Foxeer Reaper Extreme VTX table

presets/4.3/vtx/Foxeer_Reaper_Extreme.txt
Harvey from Foxeer verified the output levels with an actual VTX and confirmed with the VTX developers that the powerlevels should be as follows due to the "peculiarity" of the VTX firmware implementation:
Original PR:
https://github.com/betaflight/firmware-presets/pull/280
=> Foxeer Extreme VTX table fix: powerlevels to patch VTX firmware issue

presets/4.3/other/Tehllama_5in_1900-2250KV_FreedomSpec_3S-5S-6S_Race_TUNE_OTHER.txt
Minor housekeeping change on the Llama Freedom preset.
I realized I retained vbat_sag_compensation on the 3S tune... which explains why I was consistently launching first, hardest, and showing up to the first gate last.   I are dumb.
Added a few KV options for the TexasSpec limiting, for the Championship motors and various XNova/BH 2222KV offerings
Arranged a couple more options to prepare this preset for BF4.4 down the road.
=> Update Llama Freedom (TUNE-Other) Preset: Remove VBat_Sag_Compensation from 3S Tune, Added KV Options

presets/4.3/vtx/OpenVTx.txt
This PR adds the MSP option to the OpenVTx preset.
Since the normal MSP setup requires 4 user steps (select port, baud, msp-vtx, and enter the CLI to set MSP to half duplex) I have tried to simplify this for the users by added the port selection to the preset.  A single check and everything is auto setup 😃 
There are also minor changes to the KEYWORDS and to uncheck TRAMP as the default.  MSP should be encouraged due to the auto configuration of the VTx tables.  Should the DISCUSSION be updated to also include this PR?
To test, OpenVTx master can be flashed with PIO or a binary downloaded from [here ](https://github.com/OpenVTx/OpenVTx/pull/40#issuecomment-1170598763) and the Configurator used to upload https://openvtx.org/
=> Adds MSP option to OpenVTx

presets/4.4/vtx/HDZero.txt
added a 4.4 preset for the range of HDZERO vtxs that includes the ability to setup up the MSP VTX serial settings from the preset...  
more information about the MSP VTX settings and use in this PR https://github.com/betaflight/betaflight/pull/11705
=> add 4.4 preset for HDZERO vtxs including MSP VTX setup 

presets/4.4/tune/defaults.txt
New Antigravity Settings:
set anti_gravity_gain = 80
set anti_gravity_cutoff_hz = 5
set anti_gravity_p_gain = 100
This is part of the dependency chain to enable new Tune and TUNE_OTHER presets to exist for Betaflight 4.4
Revised Antigravity settings require these changes - placed the defaults (as of 2022.10.14 build), 
otherwise the OFFICIAL default tune remains unchaged,.
=> Update defaults.txt for Betaflight 4.4

presets/4.4/other/Tehllama_5in_Race_Spec_Multi.txt
Preset for Betaflight 4.4 (Tested using the 2022.10.14 Nightly)
This is intended to be a 'set it and forget it' Spec Racing preset.
Once user sets Motor KV, Filter Flavor (non-RPM, Safe, Spicy), Feature Selection...
this will automatically set up an array of 3S, 4S, 5S, and 6S tunes based on motor KV with matching filters.
Master Slider increments are locked to 0.05 increments, and end user adjustable after flashing preset
// This is the TexasSpec Twin of Pull Request #301 
For virtually EVERY combination, the output is a half-power spec indexed on running a 3S battery on a 1950KV quad.
These are a progression of the existing trio of Llama 5in Race Presets - Merged into a single preset, with Spicy/NonSpicy/nonRPM versions enabled for Filter and Tune
The really long list of Motor KV …
=> Llama TexasSpec Unified Multivoltage (Betaflight 4.4) Preset (3-6S, 1600-2750KV, TexasSpec Output)

presets/4.4/other/Tehllama_5in_Race_Multivoltage.txt
Preset for Betaflight 4.4 (Tested using the 2022.10.14 Nightly)
Once user sets Motor KV, Filter Flavor (non-RPM, Safe, Spicy), Feature Selection...
this will automatically set up an array of 3S, 4S, 5S, and 6S tunes based on motor KV with matching filters.
Master Slider increments are locked to 0.05 increments, and end user adjustable after flashing preset
// Key Update Milestones
- Will update on feature freeze date
- Will update on all namespace changes related to Tune profiles or Filtering
- Will update on Release Candidate 0
- Will review on all release candidates
// Dependency Chains Identified [This is why the error checker will throw errors until these items are present in MASTER
/// See Pull Request #300 
- * presets/4.4/tune/defaults.txt 
!!! This file requires an update due to …
=> Create Tehllama Llama 5in Race (Betaflight 4.4) Preset [Unified Multivoltage 3/4/5/6-S Tune for 1600-2750KV]

presets/4.4/tune/mouse_fpv/mouseFPV_AOS_35_tune_filters.txt, presets/4.4/tune/mouse_fpv/mouseFPV_Digipick_braced.txt, presets/4.4/tune/mouse_fpv/mouseFPV_FFVCycle_Incisor_PT5_tune_filters.txt, presets/4.4/tune/mouse_fpv/mouseFPV_FPVCycle_Sonicare_tune_filters.txt, presets/4.4/tune/mouse_fpv/mouseFPV_toothpick3_3s.txt
A simple port for @rochford77 (mouseFPV) presets to 4.4
Mostly copy-paste. Changes:
- include 4.4 tune defaults
- removing AG values, leaving them 4.4 defaults
- indentation
=> Ported mouseFPV tunes 4.3->4.4, removed AG values

presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_5_Inch_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_6_and_EasyTune.txt, presets/4.4/tune/supafly_fpv/SupaflyFPV_Freestyle_7_Inch_EasyTune.txt
A simple port for @SupaflyFPV presets to 4.4
Mostly copy-paste. Changes:
- include 4.4 tune defaults
- removing AG values, leaving them 4.4 defaults
- changing all to experimental (till 4.4 AG values are defined and tested)
- indentation
=> Ported SupaflyFPV tunes 4.3->4.4, removed AG values, marked as experimental

presets/4.3/filters/karate_array.txt, presets/4.4/tune/karate/karate_freestyle_5_inch.txt, presets/4.4/tune/karate/karate_race.txt, presets/4.4/tune/karate/karate_race_lite.txt, presets/4.4/tune/karate/tiny_karate.txt
This is just a simple port from 4.3 to 4.4 for the Karate tunes/filters by @sugaarK. Mostly copy-paste.
Filters stay the same so far.
Tunes require new AG settings so leaving them at defaults until further testing. Marking 4.4 tunes as experimental.
Leaving discussion links the same as for 4.3
=> Karate tunes 4.3->4.4 port

presets/4.4/tune/uav_tech/UAV_tech_5in.txt, presets/4.4/tune/uav_tech/UAV_tech_6-7in.txt, presets/4.4/tune/uav_tech/UAV_tech_8-9in.txt, presets/4.4/tune/uav_tech/UAV_tech_8-9in_Cinelifter.txt, presets/4.4/tune/uav_tech/UAV_tech_Cinewhoop.txt, presets/4.4/tune/uav_tech/UAV_tech_Toothpic.txt, presets/4.4/tune/uav_tech/UAV_tech_Whoop.txt
A simple port for @spatzengr presets to 4.4
Mostly copy-paste. Changes:
- include 4.4 tune defaults
- removing AG values, leaving them 4.4 defaults
- changing all to experimental (till 4.4 values are defined and tested)
- indentation, trailing spaces
=> Porting UAV_tech presets 4.3->4.4

presets/4.4/other/Tehllama_5in_Race_Multivoltage.txt
Did some more testing, the spicy tune filter fade range at 111Hz  was a little bit too spicy for my liking - if a pilot wants to run a more aggressive tune than this, they would be better off running Karate or MCK.
Matching Revision coming for the Llama-5in-SpecOnly
=> Llama 5in MultiVoltage Mega Tune - Fix Spicy Tune RPM Filter Fade Range to 77

presets/4.3/tune/tiny_karate.txt, presets/4.4/tune/karate/tiny_karate.txt
The more i think about motor_poles the more i lean towards that we should allow it outside of the options in TUNE/filters presets.
But only in the cases like tinywhoops, for example or Tiny Trainers. When the chances of swapping motors to a different pole count is pretty much zero.
=> Tiny_karate: added motor_poles = 12

presets/4.4/vtx/HDZero.txt
displayport_msp_serial is not an option in 4.4 anymore. use ports tab instead.
=> removed residuals "displayport_msp_serial"

presets/4.3/tune/mouseFPV_toothpick3_3s.txt, presets/4.4/tune/mouse_fpv/mouseFPV_toothpick3_3s.txt
This preset has been out for a while, and the only feedback I have received was that some users needed to back off their master just a hair, though this was seemingly rare. This lowers the master a touch to make this work for the most people. Also cleaned up some wording that no longer makes since with the fall of the mpu6000 as our primary gyro, and cleaned up a bad comment.
This also updated the preset to COMMUNITY
This contains 2 files, however the changes are consistent between the 2 files, just updating both 4.4 and 4.3
=> mouseFPV TP3 Preset updates for 4.3 and 4.4

presets/4.3/tune/mouseFPV_AOS_35_tune_filters.txt, presets/4.3/tune/mouseFPV_Digipick_braced.txt, presets/4.3/tune/mouseFPV_FFVCycle_Incisor_PT5_tune_filters.txt, presets/4.3/tune/mouseFPV_FPVCycle_Sonicare_tune_filters.txt, presets/4.4/tune/mouse_fpv/mouseFPV_AOS_35_tune_filters.txt, presets/4.4/tune/mouse_fpv/mouseFPV_Digipick_braced.txt, presets/4.4/tune/mouse_fpv/mouseFPV_FFVCycle_Incisor_PT5_tune_filters.txt, presets/4.4/tune/mouse_fpv/mouseFPV_FPVCycle_Sonicare_tune_filters.txt
Update outdated f4/f7 comments, move presets to COMMUNITY. This changes several files, but all changes are consistent to all the files, and none touch any actual commands, just labels, comments, and wording. Changes for both 4.3 and 4.4 presets.
=> Update outdate f4/f7 comments, move presets to COMMUNITY

presets/4.4/tune/quadmcfly/QuadMcFly_5_Inch_Freestyle.txt
Mid-weight freestyle build with options for Dshot 600 and Dshot 300. RPM Filtering required. Update from broken pull request #383
=> Add QuadMcFly 5in Freestyle Tune

presets/4.4/rc_link/FrSky R9 (6.67ms).txt
Due to missing FrSky R9 preset, I created RC LINK preset with modified setpoint and feedforward filtering.
I've included port selection, a choice connection the RX to the FC (Serial_RX_inversion), and various filtering options depending on intended flight style.
=> Add FrSky R9 RC link preset (FPORT, 6.67 ms mode)

presets/4.3/vtx/Unify_Pro32_Nano_SA2_1.txt
The present value of 36 (1.6w) is for the Pro32 HV and not the Pro32 Nano. Corrected to 28 (500mw+) per TBS spec sheet.
=> Update Unify_Pro32_Nano_SA2_1 Power Levels.txt

presets/4.3/vtx/HDZero.txt, presets/4.4/vtx/HDZero.txt
- Remove invalid command for 4.3 preset (`set vcd_video_system = HD` is not a valid option prior to BF 4.4)
- Tidy up option list for both presets (4.3 & 4.4)
- Activate `FORCE_OPTIONS_REVIEW` for both presets (4.3 & 4.4)
=> Update HDZero VTX preset

presets/4.3/rates/533.txt, presets/4.3/rates/Headsup.txt
Rates are almost identical, except Headsup flies 633 deg/sec for roll now.
Headsup rates:
Legacy 533 rates:
=> 533 rates update + Headsup rates

presets/4.3/rates/Nice.txt
Mr Nice (Neil Marek - Grower) is a big figure in US drone racing.
Talented racer, professional cinematic drone pilot, expert in everything, famous track designer (Velocidrone, and real life tracks), and Tthe Shitpilot.
=> Grower (Mr Nice) rates

presets/4.4/other/100-euro-fpv-tune.txt
Hi,
I created this tune as part of my frame bundle [[100-euro-fpv.com](url)] and now sharing it as a preset for BFC.
It contains multiple category changes - a full setup from a blank 4.4 flash, hence why it falls under the OTHER category.
Thanks for looking into this
Tony
=> Add TUNE to OTHER category

presets/4.5/vtx/HDZero.txt
Created a BF 4.5 Version of the HDZERO VTX preset to add in the disable colored warnings as they are currently not compatible with HDZERO.
Tested from my fork as a source.
=> disable colored warnings for HDZERO Preset in 4.5

presets/4.3/vtx/AKK_FX2_Dominator_2W.txt, presets/4.3/vtx/GepRC_RAD_2W5.txt, presets/4.3/vtx/JHEMCU_2W5.txt, presets/4.3/vtx/PandaRC_VT5804_BAT_2W5.txt
VTX tables for:
- AKK FX2 Dominator 2W
- GepRC RAD 2.5W
- JHEMCU 2.5W
- PandaRC VT5804 BAT 2.5W
All tables received from manufacturers directly
=> VTX tables for some popular long range transmitters

presets/4.5/rates/ZoeFPV_3D_rates.txt
first part of making a ZoeFPV 3d profile. this preset will overwrite all your rate profiles with Zoes different rate profiles 
Zoes legendary rate profile that she’s used for years, along with 2 variations of it depending on your own style and feel, plus KittFPV’s rates for a more linear and locked in experience. 
Each rate has been tested for it’s ability to do chaotic 3D maneuvers, and for tight tic-tocs.
=> rates for zoeFPV

presets/4.5/leds/LED VTX  race mode.txt, presets/4.5/leds/quaddiction_tinytrainer.txt
These presets allow you to set your LED colours via your VTX channel and change when you change channel. Behaviour was changed with this pr  https://github.com/betaflight/betaflight/pull/13096#discussion_r1411284423
=> fix up LED presets to work with changes to LED race mode

presets/4.5/tune/defaults.txt
Continuation of this PR:
https://github.com/betaflight/firmware-presets/pull/429
few params are renamed/added in comparisson with 4.4 tune defaults.
I also made this list in the same order it appears in CLI for easier maintenance in the future.
Plus i have removed these two parameters as they probably don't belong to tuning:
```
vbat_warning_cell_voltage
motor_pwm_rate
```
these three parameters might be renamed:
```
set tpa_rate_lower = 20
set tpa_breakpoint_lower = 1050
set tpa_breakpoint_lower_fade = ON
```
if this PR is merged:
https://github.com/betaflight/betaflight/pull/13206
but thats an easy fix
=> 4.5 tune defaults changes

presets/4.5/filters/defaults.txt
This PR is the first PR in the sequence of transferring tune/filter presets for 4.5.
My dream about full transfer defaults to PG groups can't become true yet.
The main reason that `PG_GYRO_CONFIG` includes some stuff that's hardware/user related.
And that `PG_PID_PROFILE` contains d-term filters.
So for 4.5 filters defaults can only use:
`defaults group_id 554 nosave # PG_DYN_NOTCH_CONFIG`
`defaults group_id 544 nosave # PG_RPM_FILTER_CONFIG`
which I did here.
the rest of the parameters should be listed explicitly.
I listed them in the order they appear in CLI, that's easier to maintain.
The next PRs will be:
1. 4.5 tune defaults
2. Remove 4.5 firmware from previous tunes/filters presets
3. Copy filter/tune presets over to 4.5 folder and tag them as 4.5
=> 4.5 filter defaults

presets/4.3/filters/karate_array.txt, presets/4.5/filters/basic_no_rpm_clean.txt, presets/4.5/filters/basic_no_rpm_noisy.txt, presets/4.5/filters/basic_no_rpm_normal.txt, presets/4.5/filters/basic_no_rpm_very_clean.txt, presets/4.5/filters/basic_no_rpm_very_noisy.txt, presets/4.5/filters/basic_rpm_clean.txt, presets/4.5/filters/basic_rpm_noisy.txt, presets/4.5/filters/basic_rpm_normal.txt, presets/4.5/filters/basic_rpm_very_clean.txt, presets/4.5/filters/basic_rpm_very_noisy.txt, presets/4.5/filters/ctzsnooze_race.txt, presets/4.5/filters/karate_array.txt
Three separate changes needed here:
=> 4.5 filters transfer

presets/4.5/other/100-euro-fpv-tune.txt, presets/4.5/other/Tehllama_5in_Race_Multivoltage.txt, presets/4.5/other/Tehllama_5in_Race_Spec_Multi.txt
Who is making the most complicated presets?
Or course it's @TehllamaFPV  :)
Moved three presets 4.4/other to 4.5/other, and replaced defaults with the correct ones.
=> Other presets 4.4->4.5

presets/4.3/rates/Botgrinder.txt
Betaflight and actual rates are slightly different for Botgrinder, but that's how he rolls.
=> Botgrinder rates

presets/4.4/tune/barracuda_race_tune.txt
Submitting Tune preset called the Barracuda tune. Made for 5 inch FPV racing quads. It's ideal for beginners as it keeps the motor cool with the right amount of filters but also enough pull some sharp moves. 
Preset has been tested by numerous pilots for 5 months with success. No issues on any builds. 
Sample tune in action: https://www.youtube.com/watch?v=w5hmAOC5o2M&t=47s
Preset provides warning that DSHOT 600 and bidirectional DSHOT will be enabled. 
Preset has recommendation to some RClink settings which will give this preset the perfect setting.
=> Introducing barracuda tune to betaflight

presets/4.4/tune/barracuda_race_tune.txt
Moved DSHOT section to the filter section to keep things aligned and standardised.
=> Barracuda filter option

presets/4.4/tune/barracuda_race_tune.txt, presets/4.5/tune/barracuda_race_tune.txt
Requesting to change the status of this preset to COMMUNITY. The Barracuda tune has been widely accepted by pilots around the region.  It has been proven to keep motors cool while still providing power for top racers to perform with the conditions that the frame nuts and screws are nice and tight.
=> Change to community

presets/4.3/vtx/speedybee_ultra.txt
[Product link](https://www.speedybee.com/speedybee-tx-ultra/)
VTX tables from manufacturer are attached:
* [SpeedyBee-TX ULTRA.EU.json](https://github.com/betaflight/firmware-presets/files/15061997/SpeedyBee-TX.ULTRA.EU.json)
* [SpeedyBee-TX ULTRA.USA.json](https://github.com/betaflight/firmware-presets/files/15061998/SpeedyBee-TX.ULTRA.USA.json)
=> Add SpeedyBee Ultra VTX tables

presets/4.4/filters/aos_rc/aos_t3_filters.txt, presets/4.4/tune/aos_rc/aos_t3_tune.txt, presets/4.5/filters/aos_rc/aos_t3_filters.txt, presets/4.5/tune/aos_rc/aos_t3_tune.txt
Identical to previous AOS presets in form and function. This preset is for the AOS T3 frame. It needs a slightly lower P:D ratio and higher dynamic idle than stock.
Configs for 4.3, 4.4 and 4.5 are included.
=> Add presets for the AOS T3

presets/4.5/rates/rubberquads_team_rates.txt
Since rate-profile names are only allowed 8 characters -> see PR name
=> sacrified the underscores

presets/4.5/tune/UWL-FreshBread.txt
This is a Underground Whoop League (UWL) tune  created by FreshBread.
=> Created UWL Whoop tune by FreshBread

presets/4.5/other/multigp_pro_spec.txt
Category: other, because it includes bunch of stuff that's not tune.
Almost full setup for MultiGP PRO Spec drones (7", 6S, ~1100g).
Not included: rates, LED setup, analog VTX tables, ports, motor remapping, board alignment, OSD elements.
=> MultiGP PRO Spec tune - OTHER

presets/4.5/filters/aos_rc/aos_65mm_filters.txt, presets/4.5/tune/aos_rc/aos_65mm_tune.txt
A simple filter and PID tune for 65mm Tiny Whoops based on the BetaFPV Air65 with 23000KV motors. I hope it helps!
=> AOS 65mm Tiny Whoop Tune

presets/4.5/vtx/HDZero.txt
- https://discord.com/channels/868013470023548938/930285779077459968/1256901718537408532
- untested.
- note: HDZero sends tables from MSP overwriting any user config.
- note: HDZero's table uses the text `CUSTOM` not `FACTORY`. unsure of any significance of such.
=> HDZero VTX Table update

presets/4.4/osd/YarosFPV_DJI_O3_OSD.txt
I forgot to add `#$ PARSER: MARKED` originally so the image example of my OSD wouldn't show in Betaflight.
Now it does 🙃
=> Fixed image display on YarosFPV OSD preset

presets/4.3/rates/SugarK_whoop.txt, presets/4.5/tune/karate/karate_whoop_late_2024.txt
late 2024 light weight whoop race tune. developed with real black boxing thanks to the Betafpv 5n1. tested on NBD hummingbird v3 RS and Happy Model MOB 65 HDZ aio
=> new karate whoop tune late 2024

presets/4.5/vtx/BetaFPV_AirFC.txt
Fixed the link that didn't work in my BetaFPV AirFC VTX Table preset.
=> Fixed the link for the BetaFPV AirFC VTX Table

presets/4.5/filters/aos_rc/aos_cine20_filters.txt, presets/4.5/filters/aos_rc/aos_cine25_filters.txt, presets/4.5/filters/aos_rc/aos_cine30_filters.txt, presets/4.5/filters/aos_rc/aos_cine35_filters.txt, presets/4.5/filters/aos_rc/aos_cine40_filters.txt, presets/4.5/tune/aos_rc/aos_cine20_tune.txt, presets/4.5/tune/aos_rc/aos_cine25_tune.txt, presets/4.5/tune/aos_rc/aos_cine30_tune.txt, presets/4.5/tune/aos_rc/aos_cine35_tune.txt, presets/4.5/tune/aos_rc/aos_cine40_tune.txt
Hi Everyone,
I'm launching some new Cine frames over the next few days and wanted to create presets so that people find them easy to tune. The tunes should be in the same style as previous submissions.
Thank you in advance for taking a look over them and I stand ready to make any alterations needed to esnure they meet our high Betaflight standards!
Also if you have any suggestions to improve the tunes based on your experience that would be incredible also.
=> Presets for new AOS Cine Frames

presets/4.5/tune/aos_rc/aos_hdzero_aio5_65mm.txt
A simple preset for 65mm drones using the HDZero AIO5 FC.
This board has no blackbox so tuning it is a little like playing darts blindfolded. This tune was made by creating an identical 65mm whoop with a blackbox chip and weighting it to match the HDZero AIO5.
That drone was tuned and the resulting settings transferred onto the AIO5 to test. I also experimented with thrust linear and found it useful for both my 65mm tunes.
=> Add hdzero AIO5 65mm preset
